import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:choke/services/audio/match_sounds.dart';
import 'package:choke/shared/providers/match_sound_provider.dart';

/// Records which cues actually reached the player behind the switch.
class _RecordingSounds implements MatchSounds {
  final List<String> played = [];
  int warmUps = 0;
  bool disposed = false;

  @override
  Future<void> warmUp() async => warmUps++;

  @override
  Future<void> playStart() async => played.add('start');

  @override
  Future<void> playEnd() async => played.add('end');

  @override
  Future<void> dispose() async => disposed = true;
}

/// Reads the little-endian integer of [length] bytes at [offset].
int _le(List<int> bytes, int offset, int length) {
  var value = 0;
  for (var i = length - 1; i >= 0; i--) {
    value = (value << 8) | bytes[offset + i];
  }
  return value;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('SilentMatchSounds', () {
    test('answers every cue without complaint', () {
      const silent = SilentMatchSounds();

      expect(
        Future.wait([
          silent.warmUp(),
          silent.playStart(),
          silent.playEnd(),
          silent.dispose(),
        ]),
        completes,
      );
    });
  });

  group('SwitchableMatchSounds', () {
    test('passes both cues through while it is on', () async {
      final inner = _RecordingSounds();
      final sounds = SwitchableMatchSounds(inner);

      await sounds.playStart();
      await sounds.playEnd();

      expect(inner.played, ['start', 'end']);
    });

    test('swallows both cues while it is off', () async {
      final inner = _RecordingSounds();
      final sounds = SwitchableMatchSounds(inner, enabled: false);

      await sounds.playStart();
      await sounds.playEnd();

      expect(inner.played, isEmpty);
    });

    test('takes a flick mid-match, in both directions', () async {
      final inner = _RecordingSounds();
      final sounds = SwitchableMatchSounds(inner);

      await sounds.playStart();
      sounds.enabled = false;
      await sounds.playEnd();
      sounds.enabled = true;
      await sounds.playEnd();

      expect(inner.played, ['start', 'end']);
    });

    test('warms up even while muted', () async {
      final inner = _RecordingSounds();
      final sounds = SwitchableMatchSounds(inner, enabled: false);

      await sounds.warmUp();

      // Otherwise the first cue after unmuting pays for an asset decode, and
      // arrives after the moment it was meant to mark.
      expect(inner.warmUps, 1);
    });

    test('disposing reaches the player behind the switch', () async {
      final inner = _RecordingSounds();

      await SwitchableMatchSounds(inner, enabled: false).dispose();

      expect(inner.disposed, isTrue);
    });
  });

  group('matchSoundsProvider', () {
    test('follows the preference without rebuilding the players', () async {
      final player = _RecordingSounds();
      final container = ProviderContainer(
        overrides: [matchSoundsPlayerProvider.overrideWithValue(player)],
      );
      addTearDown(container.dispose);

      final sounds = container.read(matchSoundsProvider);

      await sounds.playStart();
      container.read(matchSoundEnabledProvider.notifier).state = false;
      await sounds.playEnd();
      container.read(matchSoundEnabledProvider.notifier).state = true;
      await sounds.playEnd();

      // On by default, muted in between, audible again after.
      expect(player.played, ['start', 'end']);

      // Same instance throughout: watching the preference instead of listening
      // to it would tear down the prepared players on every toggle.
      expect(identical(container.read(matchSoundsProvider), sounds), isTrue);
    });
  });

  group('bundled cues', () {
    // The two WAVs are generated by tool/generate_match_sounds.py and then
    // referenced by path from three places that cannot see each other:
    // pubspec.yaml, AudioPlayerMatchSounds, and the files themselves. Nothing
    // else catches a rename until a referee presses start and hears silence.
    for (final entry in const {
      'start bell': AudioPlayerMatchSounds.startAsset,
      'end horn': AudioPlayerMatchSounds.endAsset,
    }.entries) {
      test('the ${entry.key} is a playable WAV that Flutter bundles', () async {
        // Loaded through rootBundle rather than dart:io, because that is the
        // path the app itself takes: it resolves against the asset manifest
        // Flutter actually builds, so a file sitting on disk undeclared — or
        // declared inside a comment — fails here exactly as it would on a
        // device. Reading the file directly would call that a pass.
        final bytes = (await rootBundle.load('assets/${entry.value}'))
            .buffer
            .asUint8List();

        expect(String.fromCharCodes(bytes.sublist(0, 4)), 'RIFF');
        expect(String.fromCharCodes(bytes.sublist(8, 12)), 'WAVE');
        expect(_le(bytes, 20, 2), 1, reason: 'uncompressed PCM');
        expect(_le(bytes, 24, 4), 44100, reason: 'sample rate');
        expect(_le(bytes, 34, 2), 16, reason: 'bit depth');

        // A cue nobody hears the whole of is no cue at all, and one that
        // outlasts the moment it marks is in the way. Both sit near 1.5 s.
        expect(bytes.lengthInBytes / (44100 * 2), inInclusiveRange(0.5, 3.0));
      });
    }
  });
}
