import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:choke/services/audio/match_sounds.dart';

/// Reads the little-endian integer of [length] bytes at [offset].
int _le(List<int> bytes, int offset, int length) {
  var value = 0;
  for (var i = length - 1; i >= 0; i--) {
    value = (value << 8) | bytes[offset + i];
  }
  return value;
}

void main() {
  group('SilentMatchSounds', () {
    test('answers every cue without complaint', () {
      const silent = SilentMatchSounds();

      expect(
        Future.wait([
          silent.warmUp(),
          silent.playStart(),
          silent.playEnd(),
          silent.dispose(),
        ]),
        completes,
      );
    });
  });

  group('bundled cues', () {
    // The two WAVs are generated by tool/generate_match_sounds.py and then
    // referenced by path from three places that cannot see each other:
    // pubspec.yaml, AudioPlayerMatchSounds, and the files themselves. Nothing
    // else catches a rename until a referee presses start and hears silence.
    for (final entry in const {
      'start bell': AudioPlayerMatchSounds.startAsset,
      'end horn': AudioPlayerMatchSounds.endAsset,
    }.entries) {
      test('the ${entry.key} is a playable WAV that Flutter bundles', () async {
        final file = File('assets/${entry.value}');
        expect(file.existsSync(), isTrue, reason: '${file.path} is missing');

        final header = await file.openRead(0, 44).first;
        expect(String.fromCharCodes(header.sublist(0, 4)), 'RIFF');
        expect(String.fromCharCodes(header.sublist(8, 12)), 'WAVE');
        expect(_le(header, 20, 2), 1, reason: 'uncompressed PCM');
        expect(_le(header, 24, 4), 44100, reason: 'sample rate');
        expect(_le(header, 34, 2), 16, reason: 'bit depth');

        // A cue nobody hears the whole of is no cue at all, and one that
        // outlasts the moment it marks is in the way. Both sit near 1.5 s.
        final seconds = file.lengthSync() / (44100 * 2);
        expect(seconds, inInclusiveRange(0.5, 3.0));

        expect(
          File('pubspec.yaml').readAsStringSync(),
          contains('assets/${entry.value}'),
          reason: 'an asset Flutter does not bundle cannot be played',
        );
      });
    }
  });
}
