// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'crypto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bump_generation`, `client`, `configured`, `current_generation`, `generation`, `ops`, `relay_add_locked`, `status_tx`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Register a relay with the pool and dial it.
Future<void> relayAdd({required String url}) =>
    RustLib.instance.api.crateApiRelayRelayAdd(url: url);

Future<void> relayRemove({required String url}) =>
    RustLib.instance.api.crateApiRelayRelayRemove(url: url);

/// Connect every registered relay.
Future<void> relayConnect() => RustLib.instance.api.crateApiRelayRelayConnect();

Future<void> relayDisconnect() =>
    RustLib.instance.api.crateApiRelayRelayDisconnect();

/// Drop every socket and dial again.
///
/// The pool reconnects on its own eventually, but "eventually" is measured in
/// TCP timeouts. When the app resumes we already know the sockets are suspect —
/// the OS kills them without a close frame — and the referee's next tap must
/// not wait for the kernel to work that out.
///
/// ## Why this rebuilds the relays instead of calling disconnect + connect
///
/// `nostr-sdk` 0.44's revival races its own teardown, and losing that race
/// **strands the relay permanently**. `disconnect()` stores a termination
/// permit (a tokio `Notify`) and returns with the status already `Terminated`;
/// `connect()` then flips it to `Pending` and spawns a task — which sees the
/// OLD task still registered and declines. The old task meanwhile wakes from
/// `connect_and_run`, reads `Pending` (not terminated, so it keeps going),
/// marks the relay `Disconnected`, and dies in its backoff sleep by consuming
/// the stored permit. End state: status `Disconnected`, **no task**, and
/// `connect()` is a no-op on `Disconnected` — nothing dials again until the
/// process restarts. That is the app's "no connection until I kill it" bug,
/// reproduced by the `resume never strands the transport` drill.
///
/// Nudging stragglers back to life with more disconnect/connect pairs just
/// re-enters the same race (the drill stayed red under a 20-round nudge loop).
/// The only sequence that cannot lose it is the one with no revival in it at
/// all: **remove the relay and add it back**. A removed relay's watcher ends
/// (its channel closes), and `relay_add` builds a fresh `Relay` — new `Notify`
/// with no stored permit, no zombie task, a new watcher — and dials. Pool
/// subscriptions survive by design: a newly added relay inherits them
/// (`nostr-relay-pool` inherits pool subscriptions on `add_relay`).
Future<void> relayReconnectAll() =>
    RustLib.instance.api.crateApiRelayRelayReconnectAll();

/// Publish to **one** relay and report that relay's verdict.
///
/// `true` = this relay accepted it. `false` = it rejected it (rate limits, an
/// invalid event, policy). `Err` = we never heard from it at all.
///
/// Publishing one relay at a time, rather than fanning out inside the pool, is
/// deliberate: the caller's convergence bookkeeping is per relay, and a
/// pool-level "it worked" would flatten exactly the distinction that matters.
Future<bool> relayPublish(
        {required String url, required SignedEventData event}) =>
    RustLib.instance.api.crateApiRelayRelayPublish(url: url, event: event);

/// Whether `url` answers a relay's WebSocket handshake within `timeout_ms`.
///
/// Settings vets a URL with this before saving it. The question is "is
/// something listening there", nothing more — success is the handshake
/// completing, not any Nostr traffic — which mirrors what the app accepted
/// before this probe existed.
///
/// Runs on a throwaway client, never the app's pool: the candidate joins no
/// registry, inherits none of the pool's subscriptions, and a URL the user
/// then decides not to save leaves nothing behind. `shutdown` reaps the
/// throwaway's tasks whichever way the probe went.
Future<bool> relayProbe({required String url, required int timeoutMs}) =>
    RustLib.instance.api
        .crateApiRelayRelayProbe(url: url, timeoutMs: timeoutMs);

Future<void> relaySubscribe(
        {required String subscriptionId, required FilterData filter}) =>
    RustLib.instance.api.crateApiRelayRelaySubscribe(
        subscriptionId: subscriptionId, filter: filter);

Future<void> relayUnsubscribe({required String subscriptionId}) =>
    RustLib.instance.api
        .crateApiRelayRelayUnsubscribe(subscriptionId: subscriptionId);

/// Every registered relay, connected or not. Convergence is measured against
/// this list, so it must not quietly drop the relays that are currently down.
Future<List<String>> relayUrls() =>
    RustLib.instance.api.crateApiRelayRelayUrls();

/// The subset currently connected.
Future<List<String>> relayConnected() =>
    RustLib.instance.api.crateApiRelayRelayConnected();

/// Every event arriving from any relay.
///
/// Deliberately built on the pool's raw `Message` notifications rather than its
/// de-duplicated `Event` ones: those drop events this client sent itself, and
/// events it has seen before. The app needs the relay's echo of its own matches
/// — that echo is how a second device learns the score. Filtering (NIP-40
/// expiry, addressable replacement) is the caller's job either way.
Stream<SignedEventData> relayEventStream() =>
    RustLib.instance.api.crateApiRelayRelayEventStream();

/// Fires whenever a relay goes up or down.
///
/// A connection is the caller's cue to push state that relay missed while it
/// was away; a disconnection is its cue to stop counting on it.
Stream<RelayStatusData> relayStatusStream() =>
    RustLib.instance.api.crateApiRelayRelayStatusStream();

/// A NIP-01 `REQ` filter. Empty vectors and `None` mean "unconstrained" — the
/// same shape the Dart `Filter` has, so the mapping stays honest.
class FilterData {
  final Uint16List kinds;
  final List<String> authors;
  final List<String> ids;
  final PlatformInt64? since;
  final PlatformInt64? until;
  final int? limit;

  const FilterData({
    required this.kinds,
    required this.authors,
    required this.ids,
    this.since,
    this.until,
    this.limit,
  });

  @override
  int get hashCode =>
      kinds.hashCode ^
      authors.hashCode ^
      ids.hashCode ^
      since.hashCode ^
      until.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterData &&
          runtimeType == other.runtimeType &&
          kinds == other.kinds &&
          authors == other.authors &&
          ids == other.ids &&
          since == other.since &&
          until == other.until &&
          limit == other.limit;
}

/// A relay went up, or went down.
class RelayStatusData {
  final String url;
  final bool connected;

  const RelayStatusData({
    required this.url,
    required this.connected,
  });

  @override
  int get hashCode => url.hashCode ^ connected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayStatusData &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          connected == other.connected;
}
